
#     steps:
#       # - name: Deploy to GitHub Pages
#       #   uses: peaceiris/actions-gh-pages@v3
#       #   with:
#       #     github_token: ${{ secrets.GITHUB_TOKEN }}
#       #     publish_dir: ./dist
#       - name: Start AWS EC2
#         # Run AWS Command on the GitHub Hosted runner which starts the instance using AWS authentication stored in GitHub Secrets (see below how to add)
#         run: |
#           aws ec2 start-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID }}
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

name: Deploy to AWS S3
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build processes
        run: echo "Build successfully!"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: echo "Tests passed!"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Uploading Extracted Artifacts to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ase-project-website
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1
